# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wedcast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Wedcast
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  target 'Wedcast-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  end

  target 'WedcastTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
